language: php

sudo: true

addons:
  firefox: 47.0.1
  postgresql: '9.4'
  apt:
    packages:
      - openjdk-8-jre-headless

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
#   - 7.3
  - 7.2
#   - 7.1
#   - 7.0
#   - 5.6
#   - 5.4

env:
  global:
    # Copy/paste from XMLDBEditor should not be linted.
    # Custom form elements are formatted according for formslib, which doesn't match Moodle's style.
    - IGNORE_PATHS=db/upgrade.php
    # - COVERAGE=false

  matrix:
    - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    # - MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    # - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    # - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql
    # - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    # - MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
  
  # CSS and YUI linting
  #  - moodle-plugin-ci grunt
