name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Create zip
      uses: papeloto/action-zip@v1
      with:
        files: classes/ db/ generate/ includes/ lang/ mt_awards/ mt_goals/ mt_p_annotation/ mt_p_timeline/ mt_rankings/ *.php
        dest: mt.zip
        recursive: true

    - uses: actions/upload-artifact@v1
      with:
        name: mt
        path: ${{ github.workspace }}/mt.zip

    - name: Display structure of downloaded files
      run: ls -R        
