name: Create Archive
on: [workflow_dispatch, deployment]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: copy-dist
        run: ls

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: "block_mt.zip"
          path: .
          directory: .
          type: zip
          exclusions: "*.git* *.circleci* .travis.yml .settings/* /documentation/* /tests/* *.json  *.yml* testing.txt Gruntfile.js"

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: block_mt
          path: block_mt.zip
