name: PHPCS check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: PHP Code Style (phpcs)
          uses: chindit/actions-phpcs@master
          with:
            # Folder to check code style
            dir: mt_awards/
#        - name: PHPCS check
#          uses: chekalsky/phpcs-action@v1
#          with:
#            enable_warnings: true
#            installed_paths: 'moodle-block_mt/mt_awards/'

