name: stylelint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
