name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  lint:
    name: Lint on Node.js ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: stylelint 
        uses: actions-hub/stylelint@master
        
