name: Update Version
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "version" #/\$plugin->version.*/g
          replace: "test" #$V_TIME
          include: "version.php"
