name: Update Version
on:
  workflow_dispatch:
    branches:
      - "master"

jobs:
  update-version:
    name: "Update Version.php"
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDH
          utcOffset: "-04:00"
      - name: Use current time
        env:
          V_TIME: "$plugin->version = ${{ steps.current-time.outputs.formattedTime }}"
        run: echo $V_TIME
      - uses: "actions/checkout@v3.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "version" #/\$plugin->version.*/g
          replace: "test" #$V_TIME
          include: "version.php"
