name: Update Version
on:
  workflow_dispatch:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Show version number
        run: echo "${{ steps.package-json-endpoint.outputs.endpoint }}"

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDH
          utcOffset: "-04:00"
      - name: Use current time
        env:
          V_TIME: "$plugin->version = ${{ steps.current-time.outputs.formattedTime }}"
        run: echo $V_TIME
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "$plugin->version = .*"
          replace: $V_TIME
          include: "version.php"
