name: Update Version
on:
  workflow_dispatch:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        env:
          V_VERSION: "${{ steps.package-version.outputs.current-version}}"
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDH
          utcOffset: "-04:00"
      - name: Use current time
        env:
          V_TIME: "$plugin->version = ${{ steps.current-time.outputs.formattedTime }}"
        run: echo $V_TIME
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "$plugin->version = .*"
          replace: $V_TIME
          include: "version.php"
