name: Update Version
on: [workflow_dispatch, deployment]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYYMMDDHH"
      - name: Usage
        env:
          TIME: "$plugin->version = ${{ steps.time.outputs.time }}"
        run: |
          echo $TIME

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
          V_TIME: "$plugin->version = ${{ steps.current-time.outputs.formattedTime }}"
        run: echo $V_TIME
#      - uses: actions/checkout@v2
#      - name: Find and Replace
#        uses: jacobtomlinson/gha-find-replace@master
#        with:
#          find: "$plugin->version = "
#          replace: "$plugin->version = "
#          include: "version.php"
